services:
  - type: web
    name: pisco-inventory-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_vn_exec_detect_total.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
