services:
  - type: web
    name: pisco-dashboard
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run pis1.py --server.port $PORT --server.address 0.0.0.0
