services:
  - type: web
    name: pisco-inventory-dashboard
    env: python
    plan: free

    pythonVersion: 3.11.9

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      streamlit run pis1.py --server.port=$PORT --server.address=0.0.0.0

    autoDeploy: true
